### PR TITLE
Removed .ssl part from configuration keys

### PR DESCRIPTION
**Pull request by tlipinski**
Config keys fixed with:
```
sed -i 's/ssl-config.ssl/ssl-config/g' *.txt
```

### CODE REVIEW

**Comment by ktoso** [comment]
Thanks, will make use of those though not this week... sorry for the delay, completely flooded with other things.

// cc @jrudolph in case you'd have some time

**Comment by jrudolph** [comment]
I'll just merge that for now and hope that it works...

**Comment by jrudolph** [comment]
I merged this but this doesn't help because I think we have no workflow to regenerate the old docs. Also the docs have been converted to paradox by now but I have no idea in which state this is.

**Comment by ktoso** [comment]
Yeah the docs generation is manual I think... I guess generate and commit them? I'll try

**Pull request merged**
