### PR TITLE
Re-introduce deprecated methods

### PR DESCRIPTION
**Pull request by raboof**
Without implementation: only for improved binary compatibility
with 0.4.0

### CODE REVIEW

**Comment by mkurz** [comment]
@raboof Anything missing, can I help?

**Comment by raboof** [comment]
Hmm, looks like we need at least part of `Ciphers` as well...

```
Error injecting constructor, java.lang.NoClassDefFoundError: com/typesafe/sslconfig/ssl/Ciphers$
[info]   at play.api.libs.ws.ahc.AsyncHttpClientProvider.<init>(AhcWSModule.scala:51)
[info]   at play.api.libs.ws.ahc.AsyncHttpClientProvider.class(AhcWSModule.scala:50)
```

**Comment by raboof** [comment]
> Hmm, looks like we need at least part of `Ciphers` as well...
> 
> ```
> Error injecting constructor, java.lang.NoClassDefFoundError: com/typesafe/sslconfig/ssl/Ciphers$
> [info]   at play.api.libs.ws.ahc.AsyncHttpClientProvider.<init>(AhcWSModule.scala:51)
> [info]   at play.api.libs.ws.ahc.AsyncHttpClientProvider.class(AhcWSModule.scala:50)
> ```

Ah, that's only in Play 2.7, that might no longer be relevant

**Comment by mkurz** [comment]
@raboof Did you also run `sbt mimaReportBinaryIssues`? If I set `mimaPreviousArtifacts` here
https://github.com/lightbend/ssl-config/blob/8c29624278658c372b094b0b771cb88d3636dc70/build.sbt#L22-L24
to 0.4.2, MiMa finds 79 potential problems... Or is the MiMa output not relevant here?
(0.4.2 is [what akka 2.6.18 is using](https://github.com/akka/akka/pull/31046/files#diff-ad2642dc77b3679e4ad2c7d3b2f59a2dcf48c1bf5b93a558a4fa44828315a34cL39)).

**Comment by raboof** [comment]
> @raboof Did you also run `sbt mimaReportBinaryIssues`? If I set `mimaPreviousArtifacts` here
> 
> https://github.com/lightbend/ssl-config/blob/8c29624278658c372b094b0b771cb88d3636dc70/build.sbt#L22-L24
> 
> to 0.4.2, MiMa finds 79 potential problems... Or is the MiMa output not relevant here?
> (0.4.2 is [what akka 2.6.18 is using](https://github.com/akka/akka/pull/31046/files#diff-ad2642dc77b3679e4ad2c7d3b2f59a2dcf48c1bf5b93a558a4fa44828315a34cL39)).

Well, yes and no: I only ran MiMa against 0.5.0.

The differences between 0.4.2 and 0.5.0 were already identified and reviewed, for example in https://github.com/lightbend/ssl-config/pull/302/files#diff-5634c415cd8c8504fdb973a3ed092300b43c4b8fc1e184f7249eb29a55511f91R40 . If we were going for complete safety then we shouldn't have updated ssl-config in Akka at all. On the other hand it is perhaps unlikely that downstream projects other than play-ws were using these API's, so given that it's perhaps OK to break the parts that play-ws 2.8 and later don't touch.

**Comment by mkurz** [comment]
:-1: So let's release 0.6.1 :wink:

**Comment by OlegYch** [comment]
> > Hmm, looks like we need at least part of `Ciphers` as well...
> > ```
> > Error injecting constructor, java.lang.NoClassDefFoundError: com/typesafe/sslconfig/ssl/Ciphers$
> > [info]   at play.api.libs.ws.ahc.AsyncHttpClientProvider.<init>(AhcWSModule.scala:51)
> > [info]   at play.api.libs.ws.ahc.AsyncHttpClientProvider.class(AhcWSModule.scala:50)
> > ```
> 
> Ah, that's only in Play 2.7, that might no longer be relevant

it is use in play 2.8 and akka-stream 2.6 as well:

```
[error] Category: Method being called not found
[error]   In artifact: play-ahc-ws-standalone_2.13-2.1.7.jar
[error]     In class: play.api.libs.ws.ahc.AhcConfigBuilder
[error]       In method:  $anonfun$validateDefaultTrustManager$2(play.api.libs.ws.ahc.AhcConfigBuilder, com.typesafe.sslconfig.ssl.AlgorithmChecker, java.security.cert.X509Certificate):334
[error]       Call to: com.typesafe.sslconfig.ssl.AlgorithmChecker.checkKeyAlgorithms(java.security.cert.X509Certificate)
[error]       Problem: Method not found: com.typesafe.sslconfig.ssl.AlgorithmChecker.checkKeyAlgorithms(java.security.cert.X509Certificate)
[error]       Found in: ssl-config-core_2.13-0.6.1.jar
[error]       --------
[error] Category: Class being called not found
[error]   In artifact: play-ahc-ws-standalone_2.13-2.1.7.jar
[error]     In class: play.api.libs.ws.ahc.AhcConfigBuilder
[error]       In method:  $anonfun$validateDefaultTrustManager$1(java.lang.String):330
[error]       Call to: com.typesafe.sslconfig.ssl.AlgorithmConstraintsParser$.parseAll(scala.util.parsing.combinator.Parsers$Parser, java.lang.CharSequence)
[error]       Problem: Class not found: com.typesafe.sslconfig.ssl.AlgorithmConstraintsParser$
[error]       --------
[error]       In method:  $anonfun$validateDefaultTrustManager$1(java.lang.String):330
[error]       Call to: com.typesafe.sslconfig.ssl.AlgorithmConstraintsParser$.expression()
[error]       Problem: Class not found: com.typesafe.sslconfig.ssl.AlgorithmConstraintsParser$
[error]       --------
[error]       In method:  $anonfun$validateDefaultTrustManager$1(java.lang.String):330
[error]       Access to: com.typesafe.sslconfig.ssl.AlgorithmConstraintsParser$.MODULE$
[error]       Problem: Class not found: com.typesafe.sslconfig.ssl.AlgorithmConstraintsParser$
[error]       --------
[error]       In method:  configureCipherSuites(java.lang.String[], com.typesafe.sslconfig.ssl.SSLConfigSettings):250
[error]       Call to: com.typesafe.sslconfig.ssl.Ciphers$.recommendedCiphers()
[error]       Problem: Class not found: com.typesafe.sslconfig.ssl.Ciphers$
[error]       --------
[error]       In method:  configureCipherSuites(java.lang.String[], com.typesafe.sslconfig.ssl.SSLConfigSettings):254
[error]       Call to: com.typesafe.sslconfig.ssl.Ciphers$.deprecatedCiphers()
[error]       Problem: Class not found: com.typesafe.sslconfig.ssl.Ciphers$
[error]       --------
[error]       In method:  configureCipherSuites(java.lang.String[], com.typesafe.sslconfig.ssl.SSLConfigSettings):250
[error]       Access to: com.typesafe.sslconfig.ssl.Ciphers$.MODULE$
[error]       Problem: Class not found: com.typesafe.sslconfig.ssl.Ciphers$
[error]       --------
[error]       In method:  configureCipherSuites(java.lang.String[], com.typesafe.sslconfig.ssl.SSLConfigSettings):254
[error]       Access to: com.typesafe.sslconfig.ssl.Ciphers$.MODULE$
[error]       Problem: Class not found: com.typesafe.sslconfig.ssl.Ciphers$
[error]       --------
```

**Comment by OlegYch** [comment]
@raboof note `com.typesafe.sslconfig.ssl.AlgorithmChecker.checkKeyAlgorithms` missing as well

**Comment by mkurz** [comment]
@OlegYch @raboof Sorry for my later answer, I just released play-ws 2.1.10 which should fix the reported problem: https://github.com/playframework/play-ws/releases/tag/2.1.10

**Pull request merged**
