### PR TITLE
Decomission DefaultHostnameVerifier

### LINKED ISSUE #98: Support Java 11
Should see how to work the `Unsafe` shenanigans into JDK 1.9 safely, and establish migration path.

 https://github.com/scala/scala-dev/issues/139

### LINKED ISSUE #100: HostnameChecker can be retired
I think that with 1.8, it should be possible to always specify the endpoint identification as follows:

```
sslParams.setEndpointIdentificationAlgorithm("HTTPS")
```

https://tersesystems.com/blog/2014/03/23/fixing-hostname-verification/

### PR DESCRIPTION
**Pull request by dwijnand**
Upstream https://github.com/playframework/playframework/pull/5082/commits/f35dd0946fb84c8eee623b0e3d3cdee3226118a6

Fixes #98 (verified test:compile succeeds locally)
Fixes #100

### CODE REVIEW

**Comment by dwijnand** [comment]
It's not wrong ;-)

**Comment by SethTisue** [comment]
MiMa is annoying that way

**Comment by marcospereira** [comment]
Should we add oraclejdk11 to Travis configuration?

**Comment by wsargent** [comment]
You'll want to remove the debug section from the docs (or add a note) to reflect the package removal

**Comment by dwijnand** [comment]
Good idea, @wsargent.  Do you mind reviewing if I dropped too much?

**Comment by wsargent** [comment]
@dwijnand I don't have review rights :-)

Maybe add a warning if `ssl-config.debug` is defined in config (since it no longer does anything) and refer to https://docs.oracle.com/javase/8/docs/technotes/guides/security/jsse/ReadDebug.html as the main debugging reference?

**Comment by dwijnand** [comment]
Thanks, Will.  Done.

(Btw, anyone in GitHub can review pull requests 🙂)

**Comment by wsargent** [comment]
@dwijnand https://github.com/tersesystems/debugjsse and https://github.com/tersesystems/ocapjsse#logging are better debugging solutions anyway

**Comment by SethTisue** [comment]
> trying it: scala/community-builds@2606f80

green at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk11-integrate-community-build/138/

**Comment by dwijnand** [comment]
Sounds good to me, @wsargent.

Excellent.  Thanks, @SethTisue.

**Comment by SethTisue** [comment]
@dwijnand in the Scala 2.12 community build at e.g. https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3722/ , play-ws is now failing because `DebugConfiguration` vanished. could I convince you to submit a small play-ws PR that fixes it...?

(I don't know the code, but perhaps an alternative would be to reintroduce `DebugConfiguration` here in this repo but as a deprecated no-op?)

**Comment by dwijnand** [comment]
Damn.  Just for context, the reason I dropped it is because it doesn't run on Java 11, as it's using privileged reflection actions, that are now enforced by the JVM (IIUC).

So I wonder how much play-ws actually depends on the behaviour of `DebugConfiguration`...

I'll get back to this when I'm done travelling.

**Comment by SethTisue** [comment]
thanks. it was easy to get the community build green again for now with SethTisue/play-ws@a99b2b6b325f9a0d0a101abfb20736e253dbc232 and scala/community-builds@bb8b9d2f39f7e0a645c229143f9ed73038f03073

**Comment by SethTisue** [comment]
er, well, except for:

```
[playframework] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.16/project-builds/playframework-336d962b6fcd9f1f9964169addd9c496e6290d3f/framework/src/play-ahc-ws/src/main/scala/play/api/libs/ws/ahc/AhcWSModule.scala:15: object debug is not a member of package com.typesafe.sslconfig.ssl
[playframework] [error] import com.typesafe.sslconfig.ssl.debug.DebugConfiguration
[playframework] [error]                                   ^
[playframework] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.16/project-builds/playframework-336d962b6fcd9f1f9964169addd9c496e6290d3f/framework/src/play-ahc-ws/src/main/scala/play/api/libs/ws/ahc/AhcWSModule.scala:71: not found: type DebugConfiguration
[playframework] [error]       new DebugConfiguration(loggerFactory).configure(wsClientConfig.ssl.debug)
[playframework] [error]           ^
[playframework] [error] two errors found
[playframework] [error] (Play-AHC-WS/compile:compileIncremental) Compilation failed
```

SethTisue/playframework@747409cef147d3c66ce421aad14df8cc89234d9e
scala/community-builds@b4c8d93ba92ecf65ef49b6ad82b77a6246359b62

**Comment by dwijnand** [comment]
Opened #142 to restore the debug packages.

**Pull request merged**
