### PR TITLE
Remove jdk workaround

### PR DESCRIPTION
**Pull request by wsargent**
Fix for https://github.com/lightbend/ssl-config/issues/320

### CODE REVIEW

**Comment by mkurz** [comment]
@raboof Can you trigger the build for this pull request again? Travis is using a Java version greater than 8u302 now:
```
[info] welcome to sbt 1.6.2 (Temurin Java 1.8.0_322)
```
Like described in #320 that was the requirement for this pull request to get merged.

**Comment by raboof** [comment]
Hmm, the new failure (`no matching JDK found: 8`) doesn't seem to have anything to do with the changes in this PR?

**Comment by mkurz** [comment]
Strange. Maybe clean the cache for this pull request? https://app.travis-ci.com/github/lightbend/ssl-config/caches

**Review by mkurz — APPROVED** [review]
@raboof Cleaning the cache did the trick. Please merge :+1:

**Pull request merged**
